spring:
  datasource:
    url: jdbc:h2:mem:order_integration;MODE=PostgreSQL;INIT=CREATE DOMAIN IF NOT EXISTS TIMESTAMPTZ AS TIMESTAMP WITH TIME ZONE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
